import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    root: '.',
    include: ['**/*.{test,spec}.{ts,tsx,js,jsx}'],
    exclude: ['**/node_modules/**', 'dist', '.next', 'out'],
    passWithNoTests: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: ['packages/*/src/**/*.ts', 'apps/*/src/**/*.ts'],
      exclude: ['**/*.{test,spec}.ts', '**/index.ts', '**/types/**', 'node_modules', 'dist'],
      thresholds: {
        statements: 0,
        branches: 0,
        functions: 0,
        lines: 0,
      },
    },
    reporters: ['default', 'verbose'],
    testTimeout: 10000,
    hookTimeout: 10000,
    retry: 0,
  },
  resolve: {
    alias: {
      '@conversation-platform/types': path.resolve(__dirname, 'packages/types/src'),
      '@conversation-platform/logger': path.resolve(__dirname, 'packages/logger/src'),
      '@conversation-platform/config': path.resolve(__dirname, 'packages/config/src'),
      '@conversation-platform/shared': path.resolve(__dirname, 'packages/shared/src'),
      '@conversation-platform/testing': path.resolve(__dirname, 'packages/testing/src'),
      '@conversation-platform/database': path.resolve(__dirname, 'packages/database/src'),
      '@conversation-platform/auth': path.resolve(__dirname, 'packages/auth/src'),
      '@conversation-platform/queue': path.resolve(__dirname, 'packages/queue/src'),
      '@conversation-platform/event-bus': path.resolve(__dirname, 'packages/event-bus/src'),
      '@conversation-platform/storage': path.resolve(__dirname, 'packages/storage/src'),
      '@conversation-platform/provider-framework': path.resolve(__dirname, 'packages/provider-framework/src'),
      '@conversation-platform/model-registry': path.resolve(__dirname, 'packages/model-registry/src'),
      '@conversation-platform/ai-engine': path.resolve(__dirname, 'packages/ai-engine/src'),
      '@conversation-platform/prompt-engine': path.resolve(__dirname, 'packages/prompt-engine/src'),
      '@conversation-platform/context-engine': path.resolve(__dirname, 'packages/context-engine/src'),
      '@conversation-platform/memory-engine': path.resolve(__dirname, 'packages/memory-engine/src'),
      '@conversation-platform/conversation-engine': path.resolve(__dirname, 'packages/conversation-engine/src'),
      '@conversation-platform/knowledge-engine': path.resolve(__dirname, 'packages/knowledge-engine/src'),
      '@conversation-platform/document-processor': path.resolve(__dirname, 'packages/document-processor/src'),
      '@conversation-platform/embeddings': path.resolve(__dirname, 'packages/embeddings/src'),
      '@conversation-platform/vector-search': path.resolve(__dirname, 'packages/vector-search/src'),
      '@conversation-platform/rag-pipeline': path.resolve(__dirname, 'packages/rag-pipeline/src'),
      '@conversation-platform/workflow-engine': path.resolve(__dirname, 'packages/workflow-engine/src'),
      '@conversation-platform/tool-engine': path.resolve(__dirname, 'packages/tool-engine/src'),
      '@conversation-platform/tools': path.resolve(__dirname, 'packages/tools/src'),
      '@conversation-platform/plugin-framework': path.resolve(__dirname, 'packages/plugin-framework/src'),
      '@conversation-platform/analytics-engine': path.resolve(__dirname, 'packages/analytics-engine/src'),
      '@conversation-platform/notification-engine': path.resolve(__dirname, 'packages/notification-engine/src'),
      '@conversation-platform/audit': path.resolve(__dirname, 'packages/audit/src'),
      '@conversation-platform/channel-core': path.resolve(__dirname, 'packages/channel-core/src'),
      '@conversation-platform/webhook-service': path.resolve(__dirname, 'services/webhook-service/src'),
      '@conversation-platform/channel-service': path.resolve(__dirname, 'services/channel-service/src'),
      '@conversation-platform/integration-service': path.resolve(__dirname, 'services/integration-service/src'),
      '@conversation-platform/channel-website': path.resolve(__dirname, 'channels/website/src'),
      '@conversation-platform/channel-whatsapp': path.resolve(__dirname, 'channels/whatsapp/src'),
      '@conversation-platform/channel-instagram': path.resolve(__dirname, 'channels/instagram/src'),
      '@conversation-platform/channel-messenger': path.resolve(__dirname, 'channels/messenger/src'),
      '@conversation-platform/channel-telegram': path.resolve(__dirname, 'channels/telegram/src'),
      '@conversation-platform/channel-slack': path.resolve(__dirname, 'channels/slack/src'),
      '@conversation-platform/channel-discord': path.resolve(__dirname, 'channels/discord/src'),
      '@conversation-platform/channel-teams': path.resolve(__dirname, 'channels/teams/src'),
      '@conversation-platform/channel-email': path.resolve(__dirname, 'channels/email/src'),
      '@conversation-platform/channel-sms': path.resolve(__dirname, 'channels/sms/src'),
      '@conversation-platform/channel-api': path.resolve(__dirname, 'channels/api/src'),
      '@conversation-platform/channel-custom': path.resolve(__dirname, 'channels/custom/src'),
      '@conversation-platform/plugin-engine': path.resolve(__dirname, 'packages/plugin-engine/src'),
      '@conversation-platform/sdk': path.resolve(__dirname, 'packages/sdk/src'),
      '@conversation-platform/sdk-js': path.resolve(__dirname, 'sdk/javascript/src'),
      '@conversation-platform/sdk-react': path.resolve(__dirname, 'sdk/react/src'),
      '@conversation-platform/sdk-nextjs': path.resolve(__dirname, 'sdk/nextjs/src'),
      '@conversation-platform/sdk-node': path.resolve(__dirname, 'sdk/node/src'),
      '@': path.resolve(__dirname, 'apps/dashboard'),
    },
  },
});
