apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cp-api.fullname" . }}
  labels:
    {{- include "cp-api.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV }}
  PORT: {{ .Values.env.PORT }}
  HOST: {{ .Values.env.HOST }}
