{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cp-api.fullname" . }}-postgres
  labels:
    {{- include "cp-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}
{{- end }}
---
{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cp-api.fullname" . }}-redis
  labels:
    {{- include "cp-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}
{{- end }}
